version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stepfunction-lamnda-nodejs"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xbtbsxn16kc0"
s3_prefix = "stepfunction-lamnda-nodejs"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
